name: Generate Datas

on:
  schedule: # Execute every 12 hours
    - cron: "* */12 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    steps:
      # Snake Animation
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: kavya4kavya
          svg_out_path: github-contribution-grid-snake.svg # Use relative path here

      # Push the SVG to the output branch
      - name: Push to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output # Ensure this branch exists
          build_dir: .          # Use the root directory if the output is in the current directory
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
